Repository hakadoriya/ormgen, pull requests merged in 2025-01, with the labels that each got.

#7 docs: Add reviewer/assignee checklist items and improve label checker documentation formatting
  .github/pull_request_template.md
  .github/workflows/label-checker.yml
Labels: docs

#8 build: Update .goreleaser.yaml
  .bin/goreleaser
  .goreleaser.yaml
  .versenv.env
  CREDITS
Labels: build

#10 ci(github-actions): Update auto-assign workflow to skip bot-initiated PRs and improve assignee handling
  .github/workflows/auto-assign.yml
Labels: ci

#12 ci(github-actions): Update task-list-checker workflow to skip bot-initiated PRs
  .github/workflows/task-list-checker.yml
Labels: ci

#14 refactor: Fix misc
  .bin/direnv
  .bin/gitleaks
  .bin/go-mod-all
  .bin/golangci-lint
  .bin/typos
  .github/workflows/final-newline-checker.yml
  .github/workflows/go-lint.yml
  .github/workflows/go-mod-tidy.yml
  .github/workflows/go-test.yml
  .github/workflows/task-list-checker.yml
  LICENSE
Labels: refactor

#21 feat: Add --go-table-file-only option
  internal/config/config.go
  internal/lang/go/generator/generate_each_file.go
  internal/lang/go/generator/generate_each_package.go
  internal/lang/go/generator/generate_ormopt_file.go
  internal/lang/go/generator/generate_table_file.go
  internal/lang/go/generator/generator.go
Labels: feat
