Repository hakadoriya/ormgen, pull requests merged in 2025-04, with the labels that each got.

#40 refactor: Add ormcommon package
  CREDITS
  Makefile
  examples/generated/cockroach/group/group.orm.gen.go
  examples/generated/cockroach/ormcommon/ormcommon.orm.gen.go
  examples/generated/cockroach/ormopt/ormopt.orm.gen.go
  examples/generated/cockroach/user/user.orm.gen.go
  examples/generated/mysql/group/group.orm.gen.go
  examples/generated/mysql/ormcommon/ormcommon.orm.gen.go
  examples/generated/mysql/ormopt/ormopt.orm.gen.go
  examples/generated/mysql/user/user.orm.gen.go
  examples/generated/postgres/group/group.orm.gen.go
  examples/generated/postgres/ormcommon/ormcommon.orm.gen.go
  examples/generated/postgres/ormopt/ormopt.orm.gen.go
  examples/generated/postgres/user/user.orm.gen.go
  examples/generated/spanner/group/group.orm.gen.go
  examples/generated/spanner/ormcommon/ormcommon.orm.gen.go
  examples/generated/spanner/ormopt/ormopt.orm.gen.go
  examples/generated/spanner/user/user.orm.gen.go
  examples/generated/sqlite3/group/group.orm.gen.go
  examples/generated/sqlite3/ormcommon/ormcommon.orm.gen.go
  examples/generated/sqlite3/ormopt/ormopt.orm.gen.go
  examples/generated/sqlite3/user/user.orm.gen.go
  examples/model/group/group.db.gen.go
  examples/model/user/user.db.gen.go
  internal/config/config.go
  internal/integrationtest/ormgen_test.go
  internal/lang/go/generator/ast.go
  internal/lang/go/generator/generate_each_file.go
  internal/lang/go/generator/generate_each_package.go
  internal/lang/go/generator/generate_ormopt_file.go
  internal/lang/go/generator/generator.go
  internal/lang/go/generator/templates/ormcommon/ormcommon.go
  internal/lang/go/generator/templates/ormcommon/ormcommon_test.go
  internal/lang/go/generator/templates/ormopt/deprecated_ormcommon_test.go
  internal/lang/go/generator/templates/ormopt/ormopt.go
  internal/lang/go/generator/templates/ormopt/ormopt_test.go
  internal/lang/go/generator/templates/package/each_file.go.tmpl
Labels: refactor

#41 build: go get -u github.com/hakadoriya/z.go@c922da6
  go.mod
  go.sum
  internal/lang/go/source/parse_test.go
  internal/lang/go/source/work_dir_test.go
  internal/logs/logs.go
Labels: build

#42 docs: Update comment for code generation
  internal/lang/go/generator/templates/ormcommon/ormcommon.go
  internal/lang/go/generator/templates/ormopt/ormopt.go
Labels: docs

#44 fix: Fix QueryerContext related bugs in generated code
  examples/generated/cockroach/group/group.orm.gen.go
  examples/generated/cockroach/group/ormgen.orm.gen.go
  examples/generated/cockroach/user/ormgen.orm.gen.go
  examples/generated/cockroach/user/user.orm.gen.go
  examples/generated/mysql/group/group.orm.gen.go
  examples/generated/mysql/group/ormgen.orm.gen.go
  examples/generated/mysql/user/ormgen.orm.gen.go
  examples/generated/mysql/user/user.orm.gen.go
  examples/generated/postgres/group/group.orm.gen.go
  examples/generated/postgres/group/ormgen.orm.gen.go
  examples/generated/postgres/user/ormgen.orm.gen.go
  examples/generated/postgres/user/user.orm.gen.go
  examples/generated/spanner/group/group.orm.gen.go
  examples/generated/spanner/group/ormgen.orm.gen.go
  examples/generated/spanner/user/ormgen.orm.gen.go
  examples/generated/spanner/user/user.orm.gen.go
  examples/generated/sqlite3/group/group.orm.gen.go
  examples/generated/sqlite3/group/ormgen.orm.gen.go
  examples/generated/sqlite3/user/ormgen.orm.gen.go
  examples/generated/sqlite3/user/user.orm.gen.go
  internal/lang/go/generator/templates/package/each_file.go.tmpl
  internal/lang/go/generator/templates/package/ormgen.go.tmpl
Labels: fix
